### ISSUE TITLE
Can't find my Github account on the commits.top list

### ISSUE THREAD

**Issue by ahammadshawki8** [lauripiispanen/github-top#203] opened 2021-04-27 04:41 UTC
Is this application list users under some criteria?

I am from Bangladesh(https://commits.top/bangladesh_private.html) and I have over 1100 contributions in Github(https://github.com/ahammadshawki8). But it doesn't list me whereas people with more/fewer contributions are listed.
I have set my location to Dhaka, Bangladesh like most other Bangladeshi users on the list.

So, please check this matter. I think it is a bug.

**Comment by aravindvnair99** [comment] 2021-05-21 15:27
@ahammadshawki8 It's not a bug. As mentioned on the page itself, you need 24 followers:

![image](https://user-images.githubusercontent.com/22199259/119161551-14563280-ba77-11eb-9e76-75617d4688a4.png)

But you only have 20:

![image](https://user-images.githubusercontent.com/22199259/119161591-2041f480-ba77-11eb-838c-d443fd1cfbfa.png)

Please close this invalid issue.

**Closed** 2021-05-22 03:24 UTC
